cc_library(
	name = "json_pass_through_calculator",
	srcs = ["json_pass_through_calculator.cc"],
	visibility = ["//visibility:public"],
	deps = [
		"//mediapipe/framework:calculator_framework",
		"//mediapipe/framework/port:status",
		"//mediapipe/framework/formats:landmark_cc_proto",
		"//mediapipe/framework/formats:rect_cc_proto",
		"//mediapipe/framework/formats:detection_cc_proto",
#		"//udp-streaming/formats:wrapper_hand_tracking_proto",
		"//mediapipe/framework/formats:wrapper_hand_tracking_cc_proto",
	],
	alwayslink = 1,
)
